version: '3'

services:

  mariadb:
    image: 'mariadb:10'
    ports:
      - '3310:3306'
    restart: always
    environment:
      - 'MYSQL_ROOT_PASSWORD=password'
      - 'MYSQL_DATABASE=breeders'
      - 'MYSQL_USER=mariadb'
      - 'MYSQL_PASSWORD=password'
    volumes:
      - './db-data/mariadb:/var/lib/mysql'
      - './sql/breeders_mysql.sql:/docker-entrypoint-initdb.d/create_tables.sql'

volumes:
  db-data:
    driver: local